package main

import "testing"

func TestToCamelCase(t *testing.T) {
	tests := map[string]string{
		"level_one":   "LevelOne",
		"level_two":   "LevelTwo",
		"example_key": "ExampleKey",
		"test_case":   "TestCase",
	}

	for input, expected := range tests {
		result := toCamelCase(input)
		if result != expected {
			t.Errorf("toCamelCase(%q) = %q; want %q", input, result, expected)
		}
	}
}

func TestGenerateConstants(t *testing.T) {
	keys := []string{"level_one", "level_two"}
	expected := `// Code generated by go generate; DO NOT EDIT.
package resource

const (
	LevelOne = "level_one"
	LevelTwo = "level_two"
)
`
	result, err := generateConstants(keys, "resource")
	if err != nil {
		t.Fatalf("generateConstants failed: %s", err)
	}
	if result != expected {
		t.Errorf("generateConstants() = %q; want %q", result, expected)
	}
}
